export const uiTranslations = {
  pt: {
      promo: "CONDIÇÕES ESPECIAIS: 15% OFF PARA EX-ALUNOS EM TODOS OS PLANOS",
      nav_aulas: "Aulas",
      nav_mentor: "O Mentor",
      nav_planos: "Planos",
      nav_duvidas: "Dúvidas",
      nav_assinar: "ASSINAR",
      hero_t1: "MENTORIA",
      hero_sub: "Domine a arte do Color Grading com o atalho profissional.",
      hero_cta_sub: "Comece agora e destrave seu padrão cinema",
      hero_cta: "COMECE AGORA MESMO",
      hero_cta_note: "Recomendamos seu caminho — responda o quiz abaixo.",
      psi_title: "A PSICOLOGIA DAS",
      psi_title_color: "CORES",
      psi_sub: "Como transformar a percepção através do grading",
      psi_t1: "Narrativa Visual",
      psi_d1: "A cor guia a emoção do seu público.",
      psi_t2: "Contraste Emocional",
      psi_d2: "Destaque o que importa na cena.",
      psi_t3: "Padrão Cinema",
      psi_d3: "O look das grandes produções.",
      cons_t1: "CONSULTORIA 1X1 COM QUEM JÁ TRILHOU,",
      cons_t2: "PARA QUEM QUER PEGAR OS ATALHOS",
      vis_t1: "VISÃO E PROPÓSITO",
      vis_sub: "+ DO QUE UM CURSO",
      vis_desc: "TIRE DÚVIDAS PARTICULARES SOBRE LOOKS, PROCESSOS, FERRAMENTAS, PRODUTOS ESPECÍFICOS, CARREIRA E QUALQUER ASSUNTO QUE TE IMPEÇA DE CHEGAR LÁ.",
      mod_title: "Módulos da Mentoria",
      test_title: "Feedback dos Alunos",
      quiz_title: "QUAL SEU NÍVEL DE COLOR?",
      quiz_desc: "Selecione seu momento atual para a gente te dar uma mensagem personalizada antes dos planos.",
      q1: "ESTOU COMEÇANDO AGORA",
      q2: "JÁ FAÇO COR DOS MEUS TRABALHOS",
      q3: "ATUO NA ÁREA E QUERO ME APROFUNDAR",
      q_btn: "VER PLANOS RECOMENDADOS",
      q_note: "Sua seleção aparece na seção de investimento.",
      mentor_tag: "O MENTOR",
      m1: "Leandro Lamezi é colorista, diretor de fotografia e fotógrafo, com mais de uma década de atuação no mercado audiovisual profissional, transitando entre publicidade, cinema e conteúdos de alto padrão.",
      m2: "Formado em Cinema Digital pela Universidade Metodista e Técnico em Fotografia pelo SENAC, construiu sua base técnica em grandes estruturas de pós-produção.",
      m3: "Hoje, Leandro une experiência técnica, visão estética e domínio de workflow profissional para ensinar color grading de forma estratégica, objetiva e alinhada ao mercado real.",
      price_title: "Investimento",
      p_f1: "CONTEÚDO PRÁTICO REAL",
      p_f2: "FEEDBACK AO VIVO",
      p_f3: "PROJETOS HANDS-ON",
      p_f4: "COMUNIDADE VIP",
      ex_aluno_discount: "DESCONTO DE 15% PARA EX-ALUNOS",
      pl1_name: "DIÁRIO",
      pl1_desc: "Consultoria pontual para resolver desafios específicos.",
      pl1_price: "R$ 600",
      pl1_suf: "/ o dia",
      pl1_i1: "2 horas de consultoria",
      pl1_i2: "Feedback direto",
      pl1_i3: "Tira-dúvidas prático",
      pl2_name: "MENSAL",
      pl2_desc: "Acompanhamento de curto prazo para evolução contínua.",
      pl2_price: "R$ 1.000",
      pl2_suf: "/ 2 dias",
      pl2_i1: "4 horas de consultoria",
      pl2_i2: "Análise de projetos",
      pl2_i3: "Acompanhamento",
      pl3_name: "PLANO ANUAL",
      pl3_desc: "O plano definitivo para dominar workflows reais e transformar sua carreira.",
      pl3_price: "R$ 11.000",
      pl3_suf: "/ 24 dias",
      pl3_i1: "48 horas de consultoria",
      pl3_i2: "Acesso total",
      pl3_i3: "Mentoria de carreira",
      buy_btn: "ASSINAR AGORA",
      buy_btn2: "GARANTIR VAGA",
      faq_title: "Dúvidas Frequentes",
      faq_box: "Ficou com alguma dúvida? Fale diretamente com o nosso time de suporte:",
      faq_btn: "FALAR COM SUPORTE",
      footer_desc: "Transforme sua visão artística em resultados de cinema. A maior plataforma de Color Grading da América Latina.",
      footer_p1: "Plataforma",
      footer_p2: "Ajuda",
      footer_priv: "Privacidade",
      footer_term: "Termos",
      down_app: "Download na",
      down_play: "Disponível no"
  },
  en: {
      promo: "SPECIAL CONDITIONS: 15% OFF FOR FORMER STUDENTS ON ALL PLANS",
      nav_aulas: "Classes",
      nav_mentor: "The Mentor",
      nav_planos: "Plans",
      nav_duvidas: "FAQ",
      nav_assinar: "SUBSCRIBE",
      hero_t1: "MENTORSHIP",
      hero_sub: "Master the art of Color Grading with the professional shortcut.",
      hero_cta_sub: "Start now and unlock your cinema standard",
      hero_cta: "START RIGHT NOW",
      hero_cta_note: "We recommend your path — answer the quiz below.",
      psi_title: "THE PSYCHOLOGY OF",
      psi_title_color: "COLORS",
      psi_sub: "How to transform perception through grading",
      psi_t1: "Visual Narrative",
      psi_d1: "Color guides your audience's emotion.",
      psi_t2: "Emotional Contrast",
      psi_d2: "Highlight what matters in the scene.",
      psi_t3: "Cinema Standard",
      psi_d3: "The look of big productions.",
      cons_t1: "1-ON-1 CONSULTING WITH SOMEONE WHO'S BEEN THERE,",
      cons_t2: "FOR THOSE WHO WANT THE SHORTCUTS",
      vis_t1: "VISION AND PURPOSE",
      vis_sub: "MORE THAN A COURSE",
      vis_desc: "ASK SPECIFIC QUESTIONS ABOUT LOOKS, PROCESSES, TOOLS, SPECIFIC PRODUCTS, CAREER AND ANYTHING KEEPING YOU FROM GETTING THERE.",
      mod_title: "Mentorship Modules",
      test_title: "Student Feedback",
      quiz_title: "WHAT IS YOUR COLOR LEVEL?",
      quiz_desc: "Select your current stage to get a personalized message before seeing the plans.",
      q1: "I AM JUST STARTING",
      q2: "I ALREADY COLOR MY PROJECTS",
      q3: "I WORK IN THE FIELD & WANT TO GROW",
      q_btn: "SEE RECOMMENDED PLANS",
      q_note: "Your selection will appear in the investment section.",
      mentor_tag: "THE MENTOR",
      m1: "Leandro Lamezi is a colorist, cinematographer and photographer with over a decade in the professional audiovisual market, working across high-end advertising and cinema.",
      m2: "Graduated in Digital Cinema from Metodista University and Photography Tech from SENAC, building his technical base in major post-production facilities.",
      m3: "Today, Leandro combines technical experience, aesthetic vision and workflow mastery to teach color grading strategically and aligned with the real market.",
      price_title: "Investment",
      p_f1: "REAL PRACTICAL CONTENT",
      p_f2: "LIVE FEEDBACK",
      p_f3: "HANDS-ON PROJECTS",
      p_f4: "VIP COMMUNITY",
      ex_aluno_discount: "15% DISCOUNT FOR FORMER STUDENTS",
      pl1_name: "DAILY",
      pl1_desc: "Specific consulting to solve punctual challenges.",
      pl1_price: "$ 300",
      pl1_suf: "/ day",
      pl1_i1: "2 consulting hours",
      pl1_i2: "Direct feedback",
      pl1_i3: "Practical Q&A",
      pl2_name: "MONTHLY",
      pl2_desc: "Short-term follow-up for continuous evolution.",
      pl2_price: "$ 600",
      pl2_suf: "/ month",
      pl2_i1: "4 consulting hours",
      pl2_i2: "Project analysis",
      pl2_i3: "Follow-up",
      pl3_name: "ANNUAL PLAN",
      pl3_desc: "The definitive plan to master real workflows and transform your career.",
      pl3_price: "$ 7,200",
      pl3_suf: "/ year",
      pl3_i1: "48 consulting hours",
      pl3_i2: "Full access",
      pl3_i3: "Career Mentoring",
      buy_btn: "SUBSCRIBE NOW",
      buy_btn2: "SECURE MY SPOT",
      faq_title: "Frequently Asked Questions",
      faq_box: "Still have questions? Talk directly to our support team:",
      faq_btn: "TALK TO SUPPORT",
      footer_desc: "Transform your artistic vision into cinema results. Latin America's largest Color Grading platform.",
      footer_p1: "Platform",
      footer_p2: "Help",
      footer_priv: "Privacy",
      footer_term: "Terms",
      down_app: "Download on",
      down_play: "Available on"
  }
};

export const modulesData = [
  { id: "01", img: "https://cardeal.tv/wp-content/uploads/2026/02/22222.jpg", pt: { title: "FUNDAMENTOS DE COR", desc: "O alicerce técnico indispensável.", det_h1: "Teoria da cor", det_p1: "Apresente a teoria por trás do círculo cromático e as funções das rodas de cor.", det_h2: "Color Management", det_p2: "Por que gerenciar cor é importante e noções de espaços de cor (Rec. 709, Log, HDR).", det_h3: "Leitura de scopes", det_p3: "Como interpretar Waveform e Vectorscope." }, en: { title: "COLOR FUNDAMENTALS", desc: "The indispensable technical foundation.", det_h1: "Color Theory", det_p1: "Understand the color wheel and color wheels functions.", det_h2: "Color Management", det_p2: "Why managing color is key and basics of color spaces.", det_h3: "Reading Scopes", det_p3: "How to read Waveform and Vectorscopes." } },
  { id: "02", img: "https://cardeal.tv/wp-content/uploads/2026/02/9.png", pt: { title: "CORREÇÃO PRIMÁRIA", desc: "Neutralização técnica para um look sólido.", det_h1: "Balanço de branco", det_p1: "Como equilibrar temperatura e neutralizar dominâncias.", det_h2: "Contraste", det_p2: "Definir contraste e intensidade.", det_h3: "Color Tints", det_p3: "Remover tonalidades indesejadas." }, en: { title: "PRIMARY CORRECTION", desc: "Technical neutralization for a solid look.", det_h1: "White Balance", det_p1: "How to balance temp and neutralize casts.", det_h2: "Contrast", det_p2: "Define contrast and intensity.", det_h3: "Color Tints", det_p3: "Remove unwanted color tints." } },
  { id: "03", img: "https://cardeal.tv/wp-content/uploads/2026/02/11.png", pt: { title: "SHOT MATCHING & SECUNDÁRIA", desc: "Continuidade visual e pele.", det_h1: "Shot matching", det_p1: "Igualar sequências com diferenças de exposição.", det_h2: "Secundária", det_p2: "Isolar cores e criar atmosferas.", det_h3: "Tons de pele", det_p3: "Neutralizar e isolar pele do fundo." }, en: { title: "SHOT MATCHING & SECONDARY", desc: "Visual continuity and skin.", det_h1: "Shot matching", det_p1: "Match sequences with exposure differences.", det_h2: "Secondary", det_p2: "Isolate colors and build atmosphere.", det_h3: "Skin Tones", det_p3: "Neutralize and separate skin from background." } },
  { id: "04", img: "https://cardeal.tv/wp-content/uploads/2026/02/Color-gradingPublicidade-HIPERBET@nocandy.filmDirecao-Save-SusieDirecao-de-fotografia-Luiz-1.jpg", pt: { title: "GRADING CRIATIVO", desc: "A assinatura cinematográfica.", det_h1: "Grading vs Correção", det_p1: "A diferença prática entre os dois.", det_h2: "Looks Básicos", det_p2: "Criar looks quentes/frios.", det_h3: "Análise", det_p3: "Desconstruir referências de Hollywood." }, en: { title: "CREATIVE GRADING", desc: "The cinematic signature.", det_h1: "Grading vs Correction", det_p1: "The practical difference.", det_h2: "Basic Looks", det_p2: "Build warm/cold aesthetics.", det_h3: "Analysis", det_p3: "Deconstruct Hollywood references." } },
  { id: "05", img: "https://cardeal.tv/wp-content/uploads/2026/02/Color-GradingPublicidade-Matte-Leao@chasleao-@ogilvybrasil-Diretor-de-cena-@___leobraga-@abr.jpg", pt: { title: "WORKFLOW PRO", desc: "Gestão de projetos e entrega final.", det_h1: "Round-trip", det_p1: "Trabalhar com XML e edição.", det_h2: "Organização", det_p2: "Boas práticas de estrutura de nós.", det_h3: "Entrega", det_p3: "Codecs e preparação final." }, en: { title: "PRO WORKFLOW", desc: "Project management and final delivery.", det_h1: "Round-trip", det_p1: "Work with XML and NLEs.", det_h2: "Organization", det_p2: "Best practices for node structure.", det_h3: "Delivery", det_p3: "Codecs and final prep." } }
];

export const testData = [
  { avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=100", pt: { name: "RICARDO S.", text: "Minhas imagens agora têm uma solidez cinematográfica." }, en: { name: "RICARDO S.", text: "My images now have a cinematic solidity." } },
  { avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=100", pt: { name: "ANA LUIZA", text: "O Color Management me economizou meses de estudo." }, en: { name: "ANA LUIZA", text: "Color Management saved me months of study." } },
  { avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=100", pt: { name: "BRUNO M.", text: "O suporte analisa nossos projetos reais. Essencial." }, en: { name: "BRUNO M.", text: "Support analyzes our real projects. Essential." } }
];

export const faqsData = [
  { pt: { q: "O que recebo ao assinar?", a: "Acesso ao currículo completo, aulas gravadas, RAWs, lives e feedback." }, en: { q: "What do I get upon subscribing?", a: "Access to the full curriculum, recorded classes, RAWs, lives and feedback." } },
  { pt: { q: "Qual o nível mínimo necessário?", a: "Não exigimos conhecimento prévio. O curso vai do zero ao avançado." }, en: { q: "What is the minimum level required?", a: "No prior knowledge required. The course goes from zero to advanced." } },
  { pt: { q: "Como funcionam as lives?", a: "Mensais com análise de trabalhos reais e Q&A direto com o Leandro." }, en: { q: "How do live sessions work?", a: "Monthly sessions with real project analysis and live Q&A with Leandro." } },
  { pt: { q: "Os módulos podem ser acessados em qualquer ordem?", a: "Recomendamos seguir a ordem, mas o acesso a qualquer módulo é liberado." }, en: { q: "Can modules be accessed in any order?", a: "We recommend following the order, but all modules are unlocked." } },
  { pt: { q: "Vou receber certificado?", a: "Sim, certificado de conclusão profissional disponível ao fim." }, en: { q: "Will I get a certificate?", a: "Yes, professional completion certificate is available." } },
  { pt: { q: "Posso acessar offline?", a: "A plataforma permite cache de vídeos via aplicativo mobile." }, en: { q: "Can I access offline?", a: "The platform allows video caching via the mobile app." } },
  { pt: { q: "Há suporte para dúvidas?", a: "Sim, suporte dedicado via WhatsApp e e-mail." }, en: { q: "Is there support for questions?", a: "Yes, dedicated support via WhatsApp and email." } },
  { pt: { q: "Posso parcelar?", a: "Sim, opções de parcelamento disponíveis no checkout." }, en: { q: "Can I pay in installments?", a: "Yes, installment options are available at checkout." } },
  { pt: { q: "Tem garantia?", a: "Garantia incondicional de 7 dias." }, en: { q: "Is there a guarantee?", a: "7-day unconditional guarantee." } },
  { pt: { q: "Receberei feedback direto?", a: "Sim, em planos que contemplam sessões individuais ou imersões." }, en: { q: "Will I get direct feedback?", a: "Yes, in plans that include 1-on-1 sessions or immersions." } },
  { pt: { q: "Serve para mercado profissional?", a: "Sim, focado em workflows reais de agências e produtoras grandes." }, en: { q: "Is it for the professional market?", a: "Yes, focused on real workflows of major agencies and studios." } },
  { pt: { q: "Existe projeto final?", a: "Sim, avaliamos seu grading em uma cena master para portfólio." }, en: { q: "Is there a final project?", a: "Yes, we evaluate your grading on a master scene for your portfolio." } },
  { pt: { q: "Diferencial deste curso?", a: "O foco em atalhos de mercado real, não apenas teorias rasas." }, en: { q: "What makes this course different?", a: "The focus on real market shortcuts, not just shallow theories." } }
];

export const logoUrls = [
  "https://static.wixstatic.com/media/dc7632_5c940be78966440f8ea2ae1b251617f9~mv2.png",
  "https://static.wixstatic.com/media/dc7632_30d60982dafd404ab517c636ab8db37d~mv2.png",
  "https://static.wixstatic.com/media/dc7632_d364b51b4c8d4183ba5836b3319bdc99~mv2.png",
  "https://static.wixstatic.com/media/dc7632_66a3f21c5cb74dce85a2ac0d3a7fd5ef~mv2.png",
  "https://static.wixstatic.com/media/dc7632_f8a65bd6cdfb48a6a62fb56c112b6e02~mv2.png",
  "https://static.wixstatic.com/media/dc7632_1719e6ae0ca1456498b8754250f1d0b5~mv2.png",
  "https://static.wixstatic.com/media/dc7632_33cdf019e2e949e6a5c0a9796cd916ed~mv2.png",
  "https://static.wixstatic.com/media/dc7632_730fc70111e74040af50f294ac1c1659~mv2.png",
  "https://static.wixstatic.com/media/dc7632_07828a57e3124dd6a6a1612bea6ad164~mv2.png",
  "https://static.wixstatic.com/media/dc7632_ae3d35e8355044a4ac485d9d8fd4ce08~mv2.png",
  "https://static.wixstatic.com/media/dc7632_82deebb438c0496f87dd71e01f85d772~mv2.png",
  "https://static.wixstatic.com/media/dc7632_79843b90236a40919bd2b2328a33e90e~mv2.png",
  "https://static.wixstatic.com/media/dc7632_4b2e723c6e024efea0c78846ba5791bb~mv2.png",
  "https://static.wixstatic.com/media/dc7632_eaae5c2730e740149269becc9d0dbb91~mv2.png",
  "https://static.wixstatic.com/media/dc7632_20d8f548b75144a49363563cee95f283~mv2.png",
  "https://static.wixstatic.com/media/dc7632_45f887889fb243039005f825a9b872c2~mv2.png",
  "https://static.wixstatic.com/media/dc7632_2b50a70ad32f46c6954a0f0cf548deef~mv2.png",
  "https://static.wixstatic.com/media/dc7632_15635598dc2042218054ebb9faf6b81c~mv2.png",
  "https://static.wixstatic.com/media/dc7632_bb4e0135b24b43c593a07ca5626fdbd7~mv2.png",
  "https://static.wixstatic.com/media/dc7632_ab91671b60fb4320a3ca11be4e3c6389~mv2.png"
];

export const welcomeMessages = {
  pt: [
      "Seja muito bem-vindo! Vamos construir sua base do zero até o profissional.", 
      "Que bom que você já edita! Vamos elevar suas cores ao nível das grandes produções.", 
      "Foco no topo! Vamos refinar seu workflow para o padrão internacional."
  ],
  en: [
      "Welcome! Let's build your professional foundation from scratch.", 
      "Great that you already edit! Let's elevate your colors to big production standards.", 
      "Focus on the top! Let's refine your workflow to the international standard."
  ]
};
